name: CI

env:
  # Branching
  is-merge: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}

  # Node.js
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          fetch-depth: 0

      - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2

      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Build application if affected by changes in feature branch'
        if: env.is-pull-request == 'true'
        run: npm run affected:build

      - name: 'Merge: Build application'
        if: env.is-merge == 'true'
        run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          fetch-depth: 0

      - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2

      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Lint Nx workspace
        run: npx nx workspace-lint

      - name: 'PR: Lint workspace and affected projects'
        if: env.is-pull-request == 'true'
        run: npm run affected:lint

      - name: 'Merge: Lint workspace and all projects'
        if: env.is-merge == 'true'
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          fetch-depth: 0

      - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2

      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Test affected projects'
        if: env.is-pull-request == 'true'
        run: npm run affected:test

      - name: 'Merge: Test all projects'
        if: env.is-merge == 'true'
        run: npm run test

  docs:
    name: Docs
    runs-on: ubuntu-latest
    if: ${{github.ref_name == 'main'}}

    permissions:
      contents: write

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          fetch-depth: 0

      - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2

      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Building documentation
        run: npm run docs

      - name: Deploying to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          token: ${{ secrets.TOKEN }}
