name: CI

env:
  is-merge: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}

  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set up workspace cache
        uses: ./.github/actions/with-cached-workspace

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download workspace cache
        uses: ./.github/actions/with-cached-workspace

      - name: Derive appropriate SHAs for base and head for 'nx affected' commands
        uses: nrwl/nx-set-shas@v2

      - name: 'PR: Build application if affected by changes in feature branch'
        if: env.is-pull-request == 'true'
        run: npm run affected:build

      - name: 'Merge: Build application'
        if: env.is-merge == 'true'
        run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download workspace cache
        uses: ./.github/actions/with-cached-workspace

      - name: Derive appropriate SHAs for base and head for 'nx affected' commands
        uses: nrwl/nx-set-shas@v2

      - name: Lint Nx workspace
        run: npx nx workspace-lint

      - name: 'PR: Lint workspace and affected projects'
        if: env.is-pull-request == 'true'
        run: npm run affected:lint

      - name: 'Merge: Lint workspace and all projects'
        if: env.is-merge == 'true'
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download workspace cache
        uses: ./.github/actions/with-cached-workspace

      - name: Derive appropriate SHAs for base and head for 'nx affected' commands
        uses: nrwl/nx-set-shas@v2

      - name: 'PR: Test affected projects'
        if: env.is-pull-request == 'true'
        run: npm run affected:test

      - name: 'Merge: Test all projects'
        if: env.is-merge == 'true'
        run: npm run test
