name: Publish

on:
  push:
    branches:
      - 'release/**'

env:
  # Node.js
  NODE_OPTIONS: --max-old-space-size=6144
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set up workspace cache
        uses: ./.github/actions/with-cached-workspace

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download workspace cache
        uses: ./.github/actions/with-cached-workspace

      - name: Publish packages
        run: npm run publish
