name: Publish

on:
  push:
    branches:
      - main

env:
  # Node.js
  NODE_OPTIONS: --max-old-space-size=6144
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    # if: ${{github.ref_name == 'main'}}

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: ./.github/actions/setup-node

      - name: Set up node_modules caching
        uses: ./.github/actions/with-cached-node-modules

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: setup
    # if: ${{github.ref_name == 'main'}}

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: ./.github/actions/setup-node

      - name: Set up node_modules caching
        uses: ./.github/actions/with-cached-node-modules

      - name: Check node_modules cache
        run: cd node_modules && ls -la && cd ..

      - name: Publish packages
        run: npm run publish
